# Generated by Django 4.2.16 on 2024-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockdata_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
